#!/bin/bash
# Knull CI/CD Easy Install Script with systemd
# Usage: curl -fsSL https://raw.githubusercontent.com/knullci/knull/main/install.sh | bash
# With custom port: curl -fsSL ... | bash -s -- --port 9090

set -e

REPO="knullci/knull"
BINARY_NAME="knull"
INSTALL_DIR="/usr/local/bin"
DATA_DIR="/var/lib/knull"
CONFIG_DIR="/etc/knull"
SERVICE_USER="knull"
DEFAULT_PORT=8080

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
PORT=$DEFAULT_PORT
SKIP_SERVICE=false
VERSION=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --port)
            PORT="$2"
            shift 2
            ;;
        --port=*)
            PORT="${1#*=}"
            shift
            ;;
        --version)
            VERSION="$2"
            shift 2
            ;;
        --version=*)
            VERSION="${1#*=}"
            shift
            ;;
        --no-service)
            SKIP_SERVICE=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

echo -e "${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     Knull CI/CD Installer                    ║${NC}"
echo -e "${GREEN}║     Self-hosted CI/CD Pipeline Server        ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""

# Check if running as root or with sudo
if [ "$EUID" -ne 0 ]; then
    echo -e "${YELLOW}Note: This script needs sudo access to install system services${NC}"
    SUDO="sudo"
else
    SUDO=""
fi

# Detect OS and Architecture
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

case "$ARCH" in
    x86_64)
        ARCH="amd64"
        ;;
    aarch64|arm64)
        ARCH="arm64"
        ;;
    *)
        echo -e "${RED}Error: Unsupported architecture: $ARCH${NC}"
        exit 1
        ;;
esac

case "$OS" in
    linux)
        PLATFORM="linux-${ARCH}"
        ;;
    darwin)
        PLATFORM="darwin-${ARCH}"
        echo -e "${YELLOW}Note: systemd is not available on macOS. Skipping service setup.${NC}"
        SKIP_SERVICE=true
        ;;
    *)
        echo -e "${RED}Error: Unsupported OS: $OS${NC}"
        exit 1
        ;;
esac

echo -e "Platform: ${BLUE}${PLATFORM}${NC}"
echo -e "Port: ${BLUE}${PORT}${NC}"

# Get version (use provided or fetch latest)
echo ""
if [ -n "$VERSION" ]; then
    # Remove 'v' prefix if provided
    VERSION="${VERSION#v}"
    echo -e "Using specified version: ${BLUE}v${VERSION}${NC}"
else
    echo "Fetching latest version..."
    VERSION=$(curl -s "https://api.github.com/repos/${REPO}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v?([^"]+)".*/\1/')
    
    if [ -z "$VERSION" ]; then
        # Fallback: try to get the first release (including prereleases)
        echo -e "${YELLOW}No stable release found, checking for prereleases...${NC}"
        VERSION=$(curl -s "https://api.github.com/repos/${REPO}/releases" | grep '"tag_name":' | head -1 | sed -E 's/.*"v?([^"]+)".*/\1/')
    fi
    
    if [ -z "$VERSION" ]; then
        echo -e "${RED}Error: No releases found. Please specify a version with --version${NC}"
        exit 1
    fi
    
    echo -e "Version: ${BLUE}v${VERSION}${NC}"
fi

# Download
DOWNLOAD_URL="https://github.com/${REPO}/releases/download/v${VERSION}/${BINARY_NAME}-${VERSION}-${PLATFORM}"
echo ""
echo "Downloading Knull CI..."

TMP_DIR=$(mktemp -d)
TMP_FILE="${TMP_DIR}/${BINARY_NAME}"

if ! curl -fsSL -o "$TMP_FILE" "$DOWNLOAD_URL"; then
    # Try JAR fallback
    echo -e "${YELLOW}Native binary not available, trying JAR...${NC}"
    JAR_URL="https://github.com/${REPO}/releases/download/v${VERSION}/${BINARY_NAME}-${VERSION}.jar"
    if curl -fsSL -o "${TMP_FILE}.jar" "$JAR_URL"; then
        echo -e "${GREEN}Downloaded JAR version${NC}"
        $SUDO mkdir -p "${INSTALL_DIR}"
        $SUDO mv "${TMP_FILE}.jar" "${INSTALL_DIR}/${BINARY_NAME}.jar"
        
        # Create wrapper script for JAR
        cat > "${TMP_DIR}/knull-wrapper" << 'EOF'
#!/bin/bash
exec java -jar /usr/local/bin/knull.jar "$@"
EOF
        $SUDO mv "${TMP_DIR}/knull-wrapper" "${INSTALL_DIR}/${BINARY_NAME}"
        $SUDO chmod +x "${INSTALL_DIR}/${BINARY_NAME}"
        IS_JAR=true
    else
        echo -e "${RED}Error: Download failed${NC}"
        rm -rf "$TMP_DIR"
        exit 1
    fi
else
    IS_JAR=false
    chmod +x "$TMP_FILE"
    $SUDO mv "$TMP_FILE" "${INSTALL_DIR}/${BINARY_NAME}"
fi

# Create data directory
$SUDO mkdir -p "$DATA_DIR"
$SUDO mkdir -p "$CONFIG_DIR"

# Create config file
echo "Creating configuration..."
$SUDO tee "$CONFIG_DIR/knull.conf" > /dev/null << EOF
# Knull CI/CD Configuration
# Generated by install script

# Server port
SERVER_PORT=${PORT}

# Data directory
DATA_DIR=${DATA_DIR}

# Additional Java options (for JAR version)
# JAVA_OPTS="-Xmx512m"
EOF

# Setup systemd service (Linux only)
if [ "$SKIP_SERVICE" = false ] && [ "$OS" = "linux" ]; then
    echo ""
    echo "Setting up systemd service..."
    
    # Create service user if not exists
    if ! id "$SERVICE_USER" &>/dev/null; then
        $SUDO useradd --system --no-create-home --shell /bin/false "$SERVICE_USER" 2>/dev/null || true
    fi
    
    # Set ownership
    $SUDO chown -R "$SERVICE_USER:$SERVICE_USER" "$DATA_DIR" 2>/dev/null || true
    
    # Create systemd service
    if [ "$IS_JAR" = true ]; then
        EXEC_START="/usr/bin/java -jar ${INSTALL_DIR}/${BINARY_NAME}.jar --server.port=\${SERVER_PORT}"
    else
        EXEC_START="${INSTALL_DIR}/${BINARY_NAME} --server.port=\${SERVER_PORT}"
    fi
    
    $SUDO tee /etc/systemd/system/knull.service > /dev/null << EOF
[Unit]
Description=Knull CI/CD Server
Documentation=https://github.com/knullci/knull-ci-cd
After=network.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
EnvironmentFile=${CONFIG_DIR}/knull.conf
ExecStart=${EXEC_START}
Restart=on-failure
RestartSec=10
WorkingDirectory=${DATA_DIR}

# Security
NoNewPrivileges=true
PrivateTmp=true

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=knull

[Install]
WantedBy=multi-user.target
EOF

    # Reload systemd
    $SUDO systemctl daemon-reload
    
    # Enable service
    $SUDO systemctl enable knull
    
    # Start service
    echo ""
    echo "Starting Knull CI..."
    $SUDO systemctl start knull
    
    sleep 2
    
    # Check status
    if $SUDO systemctl is-active --quiet knull; then
        echo -e "${GREEN}✓ Knull CI is running!${NC}"
    else
        echo -e "${YELLOW}Warning: Service may not have started correctly${NC}"
        echo "Check logs with: sudo journalctl -u knull -f"
    fi
fi

rm -rf "$TMP_DIR"

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     Installation Complete!                   ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "Access Knull CI at: ${BLUE}http://localhost:${PORT}${NC}"
echo ""
echo "Useful commands:"
echo -e "  ${YELLOW}sudo systemctl status knull${NC}    - Check status"
echo -e "  ${YELLOW}sudo systemctl restart knull${NC}   - Restart"
echo -e "  ${YELLOW}sudo systemctl stop knull${NC}      - Stop"
echo -e "  ${YELLOW}sudo journalctl -u knull -f${NC}    - View logs"
echo ""
echo "Configuration: ${CONFIG_DIR}/knull.conf"
echo ""
echo "To change the port, edit ${CONFIG_DIR}/knull.conf and restart:"
echo "  sudo nano ${CONFIG_DIR}/knull.conf"
echo "  sudo systemctl restart knull"
